/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_example_testjni3_PlayerProxy */

#ifndef _Included_com_example_testjni3_PlayerProxy
#define _Included_com_example_testjni3_PlayerProxy
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_example_testjni3_PlayerProxy
 * Method:    getPositionX
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_example_testjni3_PlayerProxy_getPositionX
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
