/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_cpgd_arrowshooting3000_FlyingTargetProxy */

#ifndef _Included_com_cpgd_arrowshooting3000_FlyingTargetProxy
#define _Included_com_cpgd_arrowshooting3000_FlyingTargetProxy
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_cpgd_arrowshooting3000_FlyingTargetProxy
 * Method:    flyingTargetProxy
 * Signature: (IIII)J
 */
JNIEXPORT jlong JNICALL Java_com_cpgd_arrowshooting3000_FlyingTargetProxy_flyingTargetProxy
  (JNIEnv *, jobject, jint, jint, jint, jint);

/*
 * Class:     com_cpgd_arrowshooting3000_FlyingTargetProxy
 * Method:    update
 * Signature: (J)J
 */
JNIEXPORT jlong JNICALL Java_com_cpgd_arrowshooting3000_FlyingTargetProxy_update
  (JNIEnv *, jobject, jlong);

#ifdef __cplusplus
}
#endif
#endif
