/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class PlayerProxy */

#ifndef _Included_PlayerProxy
#define _Included_PlayerProxy
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     PlayerProxy
 * Method:    playerProxy
 * Signature: (II)J
 */
JNIEXPORT jlong JNICALL Java_PlayerProxy_playerProxy
  (JNIEnv *, jobject, jint, jint);

/*
 * Class:     PlayerProxy
 * Method:    getPositionX
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_PlayerProxy_getPositionX
  (JNIEnv *, jobject, jlong);

/*
 * Class:     PlayerProxy
 * Method:    getPositionY
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_PlayerProxy_getPositionY
  (JNIEnv *, jobject, jlong);

#ifdef __cplusplus
}
#endif
#endif
