/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_cpgd_arrowshooting3000_components_ArrowHudProxy */

#ifndef _Included_com_cpgd_arrowshooting3000_components_ArrowHudProxy
#define _Included_com_cpgd_arrowshooting3000_components_ArrowHudProxy
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_cpgd_arrowshooting3000_components_ArrowHudProxy
 * Method:    arrowHudProxy
 * Signature: (F)J
 */
JNIEXPORT jlong JNICALL Java_com_cpgd_arrowshooting3000_components_ArrowHudProxy_arrowHudProxy
  (JNIEnv *, jobject, jfloat);

/*
 * Class:     com_cpgd_arrowshooting3000_components_ArrowHudProxy
 * Method:    getCurrentWidth
 * Signature: (FJ)F
 */
JNIEXPORT jfloat JNICALL Java_com_cpgd_arrowshooting3000_components_ArrowHudProxy_getCurrentWidth
  (JNIEnv *, jobject, jfloat, jlong);

/*
 * Class:     com_cpgd_arrowshooting3000_components_ArrowHudProxy
 * Method:    getCurrentScale
 * Signature: (FJ)F
 */
JNIEXPORT jfloat JNICALL Java_com_cpgd_arrowshooting3000_components_ArrowHudProxy_getCurrentScale
  (JNIEnv *, jobject, jfloat, jlong);

#ifdef __cplusplus
}
#endif
#endif
