/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_cpgd_arrowshooting3000_components_TerrainProxy */

#ifndef _Included_com_cpgd_arrowshooting3000_components_TerrainProxy
#define _Included_com_cpgd_arrowshooting3000_components_TerrainProxy
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_cpgd_arrowshooting3000_components_TerrainProxy
 * Method:    terrainProxy
 * Signature: (II)J
 */
JNIEXPORT jlong JNICALL Java_com_cpgd_arrowshooting3000_components_TerrainProxy_terrainProxy
  (JNIEnv *, jobject, jint, jint, jint, jint);

/*
 * Class:     com_cpgd_arrowshooting3000_components_TerrainProxy
 * Method:    getRandomTargetPositionX
 * Signature: (FFJ)F
 */
JNIEXPORT jfloat JNICALL Java_com_cpgd_arrowshooting3000_components_TerrainProxy_getRandomTargetPositionX
  (JNIEnv *, jobject, jfloat, jfloat, jlong);

/*
 * Class:     com_cpgd_arrowshooting3000_components_TerrainProxy
 * Method:    getRandomTargetPositionY
 * Signature: (FFJ)F
 */
JNIEXPORT jfloat JNICALL Java_com_cpgd_arrowshooting3000_components_TerrainProxy_getRandomTargetPositionY
  (JNIEnv *, jobject, jfloat, jfloat, jlong);

/*
 * Class:     com_cpgd_arrowshooting3000_components_TerrainProxy
 * Method:    getRandomFlyingTargetPositionX
 * Signature: (FFJ)J
 */
JNIEXPORT jlong JNICALL Java_com_cpgd_arrowshooting3000_components_TerrainProxy_getRandomFlyingTargetPositionX
  (JNIEnv *, jobject, jfloat, jfloat, jlong);

/*
 * Class:     com_cpgd_arrowshooting3000_components_TerrainProxy
 * Method:    getRandomFlyingTargetPositionY
 * Signature: (FFJ)J
 */
JNIEXPORT jlong JNICALL Java_com_cpgd_arrowshooting3000_components_TerrainProxy_getRandomFlyingTargetPositionY
  (JNIEnv *, jobject, jfloat, jfloat, jlong);

#ifdef __cplusplus
}
#endif
#endif
