/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_cpgd_arrowshooting3000_components_ScoreProxy */

#ifndef _Included_com_cpgd_arrowshooting3000_components_ScoreProxy
#define _Included_com_cpgd_arrowshooting3000_components_ScoreProxy
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_cpgd_arrowshooting3000_components_ScoreProxy
 * Method:    scoreProxy
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_com_cpgd_arrowshooting3000_components_ScoreProxy_scoreProxy
  (JNIEnv *, jobject);

/*
 * Class:     com_cpgd_arrowshooting3000_components_ScoreProxy
 * Method:    getScore
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_com_cpgd_arrowshooting3000_components_ScoreProxy_getScore
  (JNIEnv *, jobject, jlong);

/*
 * Class:     com_cpgd_arrowshooting3000_components_ScoreProxy
 * Method:    resetScore
 * Signature: (J)J
 */
JNIEXPORT jlong JNICALL Java_com_cpgd_arrowshooting3000_components_ScoreProxy_resetScore
  (JNIEnv *, jobject, jlong);

#ifdef __cplusplus
}
#endif
#endif
