/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_cpgd_arrowshooting3000_components_PlayerProxy */

#ifndef _Included_com_cpgd_arrowshooting3000_components_PlayerProxy
#define _Included_com_cpgd_arrowshooting3000_components_PlayerProxy
#ifdef __cplusplus
extern "C" {
#endif
#undef com_cpgd_arrowshooting3000_components_PlayerProxy_PLAYER_WITH
#define com_cpgd_arrowshooting3000_components_PlayerProxy_PLAYER_WITH 84L
#undef com_cpgd_arrowshooting3000_components_PlayerProxy_PLAYER_SPACING
#define com_cpgd_arrowshooting3000_components_PlayerProxy_PLAYER_SPACING 16L
/*
 * Class:     com_cpgd_arrowshooting3000_components_PlayerProxy
 * Method:    playerProxy
 * Signature: (II)J
 */
JNIEXPORT jlong JNICALL Java_com_cpgd_arrowshooting3000_components_PlayerProxy_playerProxy
  (JNIEnv *, jobject, jint, jint);

/*
 * Class:     com_cpgd_arrowshooting3000_components_PlayerProxy
 * Method:    getPositionX
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_com_cpgd_arrowshooting3000_components_PlayerProxy_getPositionX
  (JNIEnv *, jobject, jlong);

/*
 * Class:     com_cpgd_arrowshooting3000_components_PlayerProxy
 * Method:    getPositionY
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_com_cpgd_arrowshooting3000_components_PlayerProxy_getPositionY
  (JNIEnv *, jobject, jlong);

#ifdef __cplusplus
}
#endif
#endif
