/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_arrowshooting_gameplay_level_ScoreWrapper */

#ifndef _Included_com_arrowshooting_gameplay_level_ScoreWrapper
#define _Included_com_arrowshooting_gameplay_level_ScoreWrapper
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_arrowshooting_gameplay_level_ScoreWrapper
 * Method:    scoreWrapper
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_com_arrowshooting_gameplay_level_ScoreWrapper_scoreWrapper
  (JNIEnv *, jobject);

/*
 * Class:     com_arrowshooting_gameplay_level_ScoreWrapper
 * Method:    getScore
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_com_arrowshooting_gameplay_level_ScoreWrapper_getScore
  (JNIEnv *, jobject, jlong);

#ifdef __cplusplus
}
#endif
#endif
