/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_arrowshooting_gameplay_level_TargetWrapper */

#ifndef _Included_com_arrowshooting_gameplay_level_TargetWrapper
#define _Included_com_arrowshooting_gameplay_level_TargetWrapper
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_arrowshooting_gameplay_level_TargetWrapper
 * Method:    targetWrapper
 * Signature: (IIII)J
 */
JNIEXPORT jlong JNICALL Java_com_arrowshooting_gameplay_level_TargetWrapper_targetWrapper
  (JNIEnv *, jobject, jint, jint, jint, jint);

/*
 * Class:     com_arrowshooting_gameplay_level_TargetWrapper
 * Method:    getPositionX
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_com_arrowshooting_gameplay_level_TargetWrapper_getPositionX
  (JNIEnv *, jobject, jlong);

/*
 * Class:     com_arrowshooting_gameplay_level_TargetWrapper
 * Method:    getPositionY
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_com_arrowshooting_gameplay_level_TargetWrapper_getPositionY
  (JNIEnv *, jobject, jlong);

/*
 * Class:     com_arrowshooting_gameplay_level_TargetWrapper
 * Method:    setPositionX
 * Signature: (FJ)J
 */
JNIEXPORT jlong JNICALL Java_com_arrowshooting_gameplay_level_TargetWrapper_setPositionX
  (JNIEnv *, jobject, jfloat, jlong);

/*
 * Class:     com_arrowshooting_gameplay_level_TargetWrapper
 * Method:    setPositionY
 * Signature: (FJ)J
 */
JNIEXPORT jlong JNICALL Java_com_arrowshooting_gameplay_level_TargetWrapper_setPositionY
  (JNIEnv *, jobject, jfloat, jlong);

/*
 * Class:     com_arrowshooting_gameplay_level_TargetWrapper
 * Method:    update
 * Signature: (J)J
 */
JNIEXPORT jlong JNICALL Java_com_arrowshooting_gameplay_level_TargetWrapper_update
  (JNIEnv *, jobject, jlong);

/*
 * Class:     com_arrowshooting_gameplay_level_TargetWrapper
 * Method:    collidesWith
 * Signature: (IIJ)I
 */
JNIEXPORT jint JNICALL Java_com_arrowshooting_gameplay_level_TargetWrapper_collidesWith
  (JNIEnv *, jobject, jint, jint, jlong);

#ifdef __cplusplus
}
#endif
#endif
