/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_arrowshooting_gameplay_level_ArrowHudWrapper */

#ifndef _Included_com_arrowshooting_gameplay_level_ArrowHudWrapper
#define _Included_com_arrowshooting_gameplay_level_ArrowHudWrapper
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_arrowshooting_gameplay_level_ArrowHudWrapper
 * Method:    arrowHudWrapper
 * Signature: (F)J
 */
JNIEXPORT jlong JNICALL Java_com_arrowshooting_gameplay_level_ArrowHudWrapper_arrowHudWrapper
  (JNIEnv *, jobject, jfloat);

/*
 * Class:     com_arrowshooting_gameplay_level_ArrowHudWrapper
 * Method:    getCurrentWidth
 * Signature: (FJ)F
 */
JNIEXPORT jfloat JNICALL Java_com_arrowshooting_gameplay_level_ArrowHudWrapper_getCurrentWidth
  (JNIEnv *, jobject, jfloat, jlong);

/*
 * Class:     com_arrowshooting_gameplay_level_ArrowHudWrapper
 * Method:    getCurrentScale
 * Signature: (FJ)F
 */
JNIEXPORT jfloat JNICALL Java_com_arrowshooting_gameplay_level_ArrowHudWrapper_getCurrentScale
  (JNIEnv *, jobject, jfloat, jlong);

#ifdef __cplusplus
}
#endif
#endif
