/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_arrowshooting_gameplay_level_PlayerWrapper */

#ifndef _Included_com_arrowshooting_gameplay_level_PlayerWrapper
#define _Included_com_arrowshooting_gameplay_level_PlayerWrapper
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_arrowshooting_gameplay_level_PlayerWrapper
 * Method:    playerWrapper
 * Signature: (II)J
 */
JNIEXPORT jlong JNICALL Java_com_arrowshooting_gameplay_level_PlayerWrapper_playerWrapper
  (JNIEnv *, jobject, jint, jint);

/*
 * Class:     com_arrowshooting_gameplay_level_PlayerWrapper
 * Method:    getPositionX
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_com_arrowshooting_gameplay_level_PlayerWrapper_getPositionX
  (JNIEnv *, jobject, jlong);

/*
 * Class:     com_arrowshooting_gameplay_level_PlayerWrapper
 * Method:    getPositionY
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_com_arrowshooting_gameplay_level_PlayerWrapper_getPositionY
  (JNIEnv *, jobject, jlong);

#ifdef __cplusplus
}
#endif
#endif
