/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_arrowshooting_gameplay_level_FlyingTargetWrapper */

#ifndef _Included_com_arrowshooting_gameplay_level_FlyingTargetWrapper
#define _Included_com_arrowshooting_gameplay_level_FlyingTargetWrapper
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_arrowshooting_gameplay_level_FlyingTargetWrapper
 * Method:    flyingTargetWrapper
 * Signature: (IIII)J
 */
JNIEXPORT jlong JNICALL Java_com_arrowshooting_gameplay_level_FlyingTargetWrapper_flyingTargetWrapper
  (JNIEnv *, jobject, jint, jint, jint, jint);

/*
 * Class:     com_arrowshooting_gameplay_level_FlyingTargetWrapper
 * Method:    update
 * Signature: (J)J
 */
JNIEXPORT jlong JNICALL Java_com_arrowshooting_gameplay_level_FlyingTargetWrapper_update
  (JNIEnv *, jobject, jlong);
  
  /*
 * Class:     com_arrowshooting_gameplay_level_FlyingTargetWrapper
 * Method:    collidesWith
 * Signature: (IIJ)I
 */
JNIEXPORT jint JNICALL Java_com_arrowshooting_gameplay_level_FlyingTargetWrapper_collidesWith
  (JNIEnv *, jobject, jint, jint, jlong);

#ifdef __cplusplus
}
#endif
#endif
