/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_arrowshooting_gameplay_level_TerrainWrapper */

#ifndef _Included_com_arrowshooting_gameplay_level_TerrainWrapper
#define _Included_com_arrowshooting_gameplay_level_TerrainWrapper
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_arrowshooting_gameplay_level_TerrainWrapper
 * Method:    terrainWrapper
 * Signature: (II)J
 */
JNIEXPORT jlong JNICALL Java_com_arrowshooting_gameplay_level_TerrainWrapper_terrainWrapper
  (JNIEnv *, jobject, jint, jint);

/*
 * Class:     com_arrowshooting_gameplay_level_TerrainWrapper
 * Method:    getRandomTargetPositionX
 * Signature: (FFJ)F
 */
JNIEXPORT jfloat JNICALL Java_com_arrowshooting_gameplay_level_TerrainWrapper_getRandomTargetPositionX
  (JNIEnv *, jobject, jfloat, jfloat, jlong);

/*
 * Class:     com_arrowshooting_gameplay_level_TerrainWrapper
 * Method:    getRandomTargetPositionY
 * Signature: (FFJ)F
 */
JNIEXPORT jfloat JNICALL Java_com_arrowshooting_gameplay_level_TerrainWrapper_getRandomTargetPositionY
  (JNIEnv *, jobject, jfloat, jfloat, jlong);

/*
 * Class:     com_arrowshooting_gameplay_level_TerrainWrapper
 * Method:    getRandomFlyingTargetPositionX
 * Signature: (FFJ)J
 */
JNIEXPORT jlong JNICALL Java_com_arrowshooting_gameplay_level_TerrainWrapper_getRandomFlyingTargetPositionX
  (JNIEnv *, jobject, jfloat, jfloat, jlong);

/*
 * Class:     com_arrowshooting_gameplay_level_TerrainWrapper
 * Method:    getRandomFlyingTargetPositionY
 * Signature: (FFJ)J
 */
JNIEXPORT jlong JNICALL Java_com_arrowshooting_gameplay_level_TerrainWrapper_getRandomFlyingTargetPositionY
  (JNIEnv *, jobject, jfloat, jfloat, jlong);

#ifdef __cplusplus
}
#endif
#endif
