/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_cpgd_arrowshooting3000_TargetProxy */

#ifndef _Included_com_cpgd_arrowshooting3000_TargetProxy
#define _Included_com_cpgd_arrowshooting3000_TargetProxy
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_cpgd_arrowshooting3000_TargetProxy
 * Method:    targetProxy
 * Signature: (IIII)J
 */
JNIEXPORT jlong JNICALL Java_com_cpgd_arrowshooting3000_TargetProxy_targetProxy
  (JNIEnv *, jobject, jint, jint, jint, jint);

/*
 * Class:     com_cpgd_arrowshooting3000_TargetProxy
 * Method:    getPositionX
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_com_cpgd_arrowshooting3000_TargetProxy_getPositionX
  (JNIEnv *, jobject, jlong);

/*
 * Class:     com_cpgd_arrowshooting3000_TargetProxy
 * Method:    getPositionY
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_com_cpgd_arrowshooting3000_TargetProxy_getPositionY
  (JNIEnv *, jobject, jlong);

/*
 * Class:     com_cpgd_arrowshooting3000_TargetProxy
 * Method:    update
 * Signature: (J)J
 */
JNIEXPORT jlong JNICALL Java_com_cpgd_arrowshooting3000_TargetProxy_update
  (JNIEnv *, jobject, jlong);

/*
 * Class:     com_cpgd_arrowshooting3000_TargetProxy
 * Method:    collidesWith
 * Signature: (IIJ)I
 */
JNIEXPORT jint JNICALL Java_com_cpgd_arrowshooting3000_TargetProxy_collidesWith
  (JNIEnv *, jobject, jint, jint, jlong);

#ifdef __cplusplus
}
#endif
#endif
