/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_cpgd_arrowshooting3000_TerrainProxy */

#ifndef _Included_com_cpgd_arrowshooting3000_TerrainProxy
#define _Included_com_cpgd_arrowshooting3000_TerrainProxy
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_cpgd_arrowshooting3000_TerrainProxy
 * Method:    terrain
 * Signature: (IIII)J
 */
JNIEXPORT jlong JNICALL Java_com_cpgd_arrowshooting3000_TerrainProxy_terrain
  (JNIEnv *, jobject, jint, jint, jint, jint);

/*
 * Class:     com_cpgd_arrowshooting3000_TerrainProxy
 * Method:    GetRandomTargetPositionX
 * Signature: (FFJ)F
 */
JNIEXPORT jfloat JNICALL Java_com_cpgd_arrowshooting3000_TerrainProxy_GetRandomTargetPositionX
  (JNIEnv *, jobject, jfloat, jfloat, jlong);

/*
 * Class:     com_cpgd_arrowshooting3000_TerrainProxy
 * Method:    GetRandomTargetPositionY
 * Signature: (FFJ)F
 */
JNIEXPORT jfloat JNICALL Java_com_cpgd_arrowshooting3000_TerrainProxy_GetRandomTargetPositionY
  (JNIEnv *, jobject, jfloat, jfloat, jlong);

/*
 * Class:     com_cpgd_arrowshooting3000_TerrainProxy
 * Method:    GetRandomFlyingStartPositionX
 * Signature: (FFJ)F
 */
JNIEXPORT jfloat JNICALL Java_com_cpgd_arrowshooting3000_TerrainProxy_GetRandomFlyingStartPositionX
  (JNIEnv *, jobject, jfloat, jfloat, jlong);

/*
 * Class:     com_cpgd_arrowshooting3000_TerrainProxy
 * Method:    GetRandomFlyingStartPositionY
 * Signature: (FFJ)F
 */
JNIEXPORT jfloat JNICALL Java_com_cpgd_arrowshooting3000_TerrainProxy_GetRandomFlyingStartPositionY
  (JNIEnv *, jobject, jfloat, jfloat, jlong);

/*
 * Class:     com_cpgd_arrowshooting3000_TerrainProxy
 * Method:    GetRandomValue
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_com_cpgd_arrowshooting3000_TerrainProxy_GetRandomValue
  (JNIEnv *, jobject, jlong);

#ifdef __cplusplus
}
#endif
#endif
