/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_cpgd_arrowshooting3000_PlayerProxy */

#ifndef _Included_com_cpgd_arrowshooting3000_PlayerProxy
#define _Included_com_cpgd_arrowshooting3000_PlayerProxy
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_cpgd_arrowshooting3000_PlayerProxy
 * Method:    playerProxy
 * Signature: (II)J
 */
JNIEXPORT jlong JNICALL Java_com_cpgd_arrowshooting3000_PlayerProxy_playerProxy
  (JNIEnv *, jobject, jint, jint);

/*
 * Class:     com_cpgd_arrowshooting3000_PlayerProxy
 * Method:    getPositionX
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_com_cpgd_arrowshooting3000_PlayerProxy_getPositionX
  (JNIEnv *, jobject, jlong);

JNIEXPORT jint JNICALL Java_com_cpgd_arrowshooting3000_PlayerProxy_getPositionY
  (JNIEnv *, jobject, jlong);

#ifdef __cplusplus
}
#endif
#endif
