/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_cpgd_arrowshooting3000_ScoreProxy */

#ifndef _Included_com_cpgd_arrowshooting3000_ScoreProxy
#define _Included_com_cpgd_arrowshooting3000_ScoreProxy
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_cpgd_arrowshooting3000_ScoreProxy
 * Method:    score
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_cpgd_arrowshooting3000_ScoreProxy_score
  (JNIEnv *, jobject);

/*
 * Class:     com_cpgd_arrowshooting3000_ScoreProxy
 * Method:    getScore
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_cpgd_arrowshooting3000_ScoreProxy_getScore
  (JNIEnv *, jobject);

/*
 * Class:     com_cpgd_arrowshooting3000_ScoreProxy
 * Method:    resetScore
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_cpgd_arrowshooting3000_ScoreProxy_resetScore
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
